# Generated by Django 5.0.7 on 2024-08-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_tasks_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
